before_install:
        - sudo apt-get install -qq ttf-sil-gentium ttf-sil-gentium-basic
        - sudo apt-get install -qq texlive-fonts-extra ttf-inconsolata ttf-droid
        - sudo apt-get install -qq texlive-xetex texlive-latex-recommended texlive-latex-extra

script: ./build.sh

